services:
  web:
    container_name: unite-control-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: unite-control-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8111/
